### ISSUE TITLE
Zenbleed microcode update

### ISSUE THREAD

**Issue by dkowis** [pop-os/amd64-microcode#1]
The microcode update: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=0bc3126c9cfa0b8c761483215c25382f831a7c6f

The context: https://lock.cmpxchg8b.com/zenbleed.html

I have at least one CPU that needs the newer microcode to mitigate a pretty gnarly bug. I don't suppose it could make it into this repo?

Thanks!

**Comment by dkowis** [comment]
https://salsa.debian.org/hmh/amd64-microcode/-/compare/main...main?from_project_id=71024

The upstream project seems to be behind a bit anyway, but maybe you could cherry pick those things?

**Comment by jackpot51** [comment]
We will pull this today
